---

  GNU nano 5.6.1                                                                                      timesync.yml                                                                                                 
---

- hosts: cluster
  gather_facts: false
  become: true
  vars:
    timesync_ntp_servers:
      - hostname: ptbtime1.ptb.de
        iburst: yes
        pool: yes
        nts: yes
  roles:
    - role: "/usr/share/ansible/roles/linux-system-roles.timesync"

- hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
