---

- hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: present

- hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Install nano
      ansible.builtin.dnf:
        name: nano
        state: present

- hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
