---

- name: Quit master server
  become: true
  ansible.builtin.command: "nats-server --signal quit"

- name: Start master server
  become: true
  ansible.builtin.command: "nats-server --cluster nats://localhost:{{ cluster_port }} --cluster_name {{ cluster_name }}"
  register: result

- name: Print result
  ansible.builtin.debug:
    var: result
