---

- name: Quit slave server
  become: true
  ansible.builtin.command: "nats-server --signal quit"

- name: Start slave server
  become: true
  command: "nats-server --cluster nats://localhost:{{ cluster_port }} --routes nats://{{ master_ip }}:{{ cluster_port }} --cluster_name {{ cluster_name }}"
  register: result

- name: Print result
  ansible.builtin.debug:
    var: result
