---

- name: Install NATS client x64
  ansible.builtin.dnf:
    name: "https://github.com/nats-io/natscli/releases/download/v{{ nats_client_version }}/nats-{{ nats_client_version }}-amd64.rpm"
  when: ansible_facts.architecture == "x86_64"
